create table if not exists approved_students (
  id bigint generated by default as identity primary key,
  course_id bigint references courses(id) on delete cascade not null,
  year int not null,
  modality_code int not null,
  rank int not null,
  name text not null,
  score float not null,
  bonus float default 0,
  call_number int not null default 1,
  status text not null default 'convocado',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  unique (course_id, year, modality_code, rank, call_number)
);

create index if not exists approved_students_course_id_idx on approved_students(course_id);
create index if not exists approved_students_year_idx on approved_students(year);

-- RLS Policies
alter table approved_students enable row level security;

create policy "Enable read access for all users"
on approved_students for select
using (true);

create policy "Enable all access for service role"
on approved_students for all
using (auth.role() = 'service_role');
